name: GitHub Actions CI and Jenkins CD

on:
  push:
    branches:
      - main

jobs:
  build-and-trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build Java Application
        run: mvn clean package

      - name: Trigger Jenkins Job
        run: |
          curl -f -X POST "${{ secrets.JENKINS_URL }}/job/insured-assurance-deploy/job/main/build" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"